BEGIN TRANSACTION
GO
INSERT INTO Pages (pName, pTitle, pText, mTitle, mDescription, mKeywords, pMasterPage, pEditDate, pBody, pHTML, pBodyFile) VALUES (N'default', N'Welcome', '<div id="lipsum">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum tellus id leo cursus, vitae commodo orci facilisis. Mauris porta suscipit semper. Praesent ut gravida mauris, vel porta massa. Morbi mauris ex, dapibus eu eleifend vel, euismod in ante. Etiam erat sapien, feugiat in pulvinar vel, vestibulum ac urna. Vivamus eu imperdiet ex, vitae consequat odio. Proin facilisis dapibus leo vitae dapibus. Aliquam a ipsum ac augue venenatis fermentum ac condimentum odio. Vestibulum quam dolor, vehicula semper ultrices nec, luctus a arcu. Aliquam aliquam justo in sem commodo, non tempus nisl scelerisque. Nullam non consectetur arcu. Sed rhoncus sodales molestie. Donec molestie, nunc sed luctus semper, tellus nunc porttitor diam, at rhoncus ex sapien eu dolor. Pellentesque posuere lorem at quam pellentesque lobortis. Etiam erat sapien, posuere vitae blandit eu, eleifend sit amet mauris. Proin faucibus risus sit amet dui blandit dapibus.</p>
<p>Etiam accumsan turpis lectus, nec lobortis ipsum egestas non. Praesent elit enim, bibendum non neque a, interdum vulputate orci. Nullam sapien nisl, tempor non risus id, dapibus tincidunt est. Nulla molestie malesuada risus. Quisque egestas felis eu lacus sodales varius. Nam pretium vulputate fringilla. Morbi nec feugiat nunc. Aliquam erat volutpat. Nulla at consequat lorem, non consequat ligula. Nunc urna lacus, elementum at tempus eget, tincidunt volutpat mauris. Duis lacinia est risus, in ornare nisi placerat vulputate. Nulla tempus condimentum purus, ut rutrum lorem. Morbi pellentesque velit quis nisl sodales, nec ullamcorper felis porta.</p>
<p>Suspendisse potenti. Pellentesque dapibus egestas sem, vel rutrum velit elementum eget. Sed ullamcorper sodales dui, sed tincidunt orci. Proin euismod odio ut massa pharetra convallis. Ut a lorem malesuada, bibendum neque quis, lobortis magna. Donec vitae pharetra urna. Donec faucibus, erat id mollis lacinia, risus nulla cursus sem, et tempor eros dui non sapien. Maecenas id laoreet est, quis porttitor arcu. Morbi ac egestas lorem.</p>
<p>Suspendisse ornare purus eu est efficitur ullamcorper. Etiam vel lectus bibendum tortor porttitor pharetra. Nunc finibus libero faucibus mi efficitur, eu viverra mauris ullamcorper. Etiam interdum est eget auctor ullamcorper. Suspendisse varius vel nulla eu accumsan. Phasellus quis nibh sem. Vestibulum augue leo, lobortis nec ex in, commodo tristique tellus. Suspendisse nibh leo, facilisis quis turpis ut, ultricies euismod ipsum. Pellentesque id dignissim justo.</p>
<p>Curabitur dictum facilisis lacus, facilisis pellentesque est commodo et. Aenean vulputate quam molestie metus imperdiet, vel accumsan arcu euismod. Quisque a risus sit amet risus imperdiet iaculis. Sed consequat felis viverra sem commodo lacinia. Duis et augue iaculis, venenatis lorem sit amet, dapibus ex. Nullam sit amet mollis metus. Vestibulum id vestibulum tortor. Pellentesque blandit vulputate auctor. Quisque laoreet lectus elit, ut tempor mi ultricies eget. Aliquam aliquam dolor id eros mollis, ut interdum nibh semper. Nullam vitae elit a leo vehicula tincidunt. Sed sit amet purus scelerisque, tincidunt ipsum eu, viverra tellus.</p>
</div>', N'Speed-Demon - Welcome', N'This is where the meta description goes.', N'this, is, where, the, meta, keywords, go', N'_SpeedDemon.cshtml', CONVERT(datetime, '2015-10-05 19:16:36', 120), '1', '1', N'_DefaultBody.cshtml');
INSERT INTO Pages (pName, pTitle, pText, mTitle, mDescription, mKeywords, pMasterPage, pEditDate, pBody, pHTML, pBodyFile) VALUES (N'about', N'About', '<div id="lipsum">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum condimentum tellus id leo cursus, vitae commodo orci facilisis. Mauris porta suscipit semper. Praesent ut gravida mauris, vel porta massa. Morbi mauris ex, dapibus eu eleifend vel, euismod in ante. Etiam erat sapien, feugiat in pulvinar vel, vestibulum ac urna. Vivamus eu imperdiet ex, vitae consequat odio. Proin facilisis dapibus leo vitae dapibus. Aliquam a ipsum ac augue venenatis fermentum ac condimentum odio. Vestibulum quam dolor, vehicula semper ultrices nec, luctus a arcu. Aliquam aliquam justo in sem commodo, non tempus nisl scelerisque. Nullam non consectetur arcu. Sed rhoncus sodales molestie. Donec molestie, nunc sed luctus semper, tellus nunc porttitor diam, at rhoncus ex sapien eu dolor. Pellentesque posuere lorem at quam pellentesque lobortis. Etiam erat sapien, posuere vitae blandit eu, eleifend sit amet mauris. Proin faucibus risus sit amet dui blandit dapibus.</p>
<p>Etiam accumsan turpis lectus, nec lobortis ipsum egestas non. Praesent elit enim, bibendum non neque a, interdum vulputate orci. Nullam sapien nisl, tempor non risus id, dapibus tincidunt est. Nulla molestie malesuada risus. Quisque egestas felis eu lacus sodales varius. Nam pretium vulputate fringilla. Morbi nec feugiat nunc. Aliquam erat volutpat. Nulla at consequat lorem, non consequat ligula. Nunc urna lacus, elementum at tempus eget, tincidunt volutpat mauris. Duis lacinia est risus, in ornare nisi placerat vulputate. Nulla tempus condimentum purus, ut rutrum lorem. Morbi pellentesque velit quis nisl sodales, nec ullamcorper felis porta.</p>
<p>Suspendisse potenti. Pellentesque dapibus egestas sem, vel rutrum velit elementum eget. Sed ullamcorper sodales dui, sed tincidunt orci. Proin euismod odio ut massa pharetra convallis. Ut a lorem malesuada, bibendum neque quis, lobortis magna. Donec vitae pharetra urna. Donec faucibus, erat id mollis lacinia, risus nulla cursus sem, et tempor eros dui non sapien. Maecenas id laoreet est, quis porttitor arcu. Morbi ac egestas lorem.</p>
<p>Suspendisse ornare purus eu est efficitur ullamcorper. Etiam vel lectus bibendum tortor porttitor pharetra. Nunc finibus libero faucibus mi efficitur, eu viverra mauris ullamcorper. Etiam interdum est eget auctor ullamcorper. Suspendisse varius vel nulla eu accumsan. Phasellus quis nibh sem. Vestibulum augue leo, lobortis nec ex in, commodo tristique tellus. Suspendisse nibh leo, facilisis quis turpis ut, ultricies euismod ipsum. Pellentesque id dignissim justo.</p>
<p>Curabitur dictum facilisis lacus, facilisis pellentesque est commodo et. Aenean vulputate quam molestie metus imperdiet, vel accumsan arcu euismod. Quisque a risus sit amet risus imperdiet iaculis. Sed consequat felis viverra sem commodo lacinia. Duis et augue iaculis, venenatis lorem sit amet, dapibus ex. Nullam sit amet mollis metus. Vestibulum id vestibulum tortor. Pellentesque blandit vulputate auctor. Quisque laoreet lectus elit, ut tempor mi ultricies eget. Aliquam aliquam dolor id eros mollis, ut interdum nibh semper. Nullam vitae elit a leo vehicula tincidunt. Sed sit amet purus scelerisque, tincidunt ipsum eu, viverra tellus.</p>
</div>', N'Speed-Demon - About', N'This is where the meta description goes.', N'this, is, where, the, meta, keywords, go', N'_SpeedDemon.cshtml', CONVERT(datetime, '2015-10-05 18:34:06', 120), '1', '1', N'_DefaultBody.cshtml');
INSERT INTO Pages (pName, pTitle, pText, mTitle, mDescription, mKeywords, pMasterPage, pEditDate, pBody, pHTML, pBodyFile) VALUES (N'contact', N'Contact', '<div id="lipsum">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec odio purus, varius sit amet nibh convallis, interdum luctus quam. Proin sed lacinia lorem. Morbi euismod lobortis nisi, eu elementum felis ullamcorper ut. Nunc condimentum posuere accumsan. Praesent sed justo tempus, vulputate turpis eget, vehicula diam. Etiam nec orci sagittis sem auctor sagittis. Ut sapien nisi, pulvinar eget lacus eget, tincidunt vehicula leo.</p>
<p>Vivamus ultricies ex eros, quis tristique nisl mollis non. Integer laoreet arcu mauris, quis ornare nulla pulvinar in. Aliquam venenatis, lorem non iaculis mattis, risus urna faucibus enim, id lobortis diam nisl sit amet odio. Mauris sed nisl tempor, fringilla massa a, vehicula mi. Ut ac ipsum dapibus, iaculis nibh vitae, aliquam neque. Suspendisse potenti. Quisque dignissim diam eget arcu faucibus lobortis. Vestibulum blandit ultricies mi sodales ullamcorper. Vestibulum quam ipsum, tincidunt et facilisis id, ornare sed augue. Integer et molestie metus. Nulla id ante eget diam commodo facilisis. Proin a dignissim mi. Mauris mollis fringilla egestas. Curabitur aliquam purus diam, eu egestas neque faucibus vitae. Praesent tincidunt tellus vitae hendrerit venenatis. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
<p>Duis egestas, nisi in dictum accumsan, mi dolor vehicula nulla, nec sodales urna quam a ipsum. Nunc vel eleifend purus, sit amet condimentum nulla. Mauris rhoncus ac sapien molestie fringilla. Vestibulum eu felis sed sapien porta auctor. Sed eros eros, placerat ac lacus ac, ornare iaculis lorem. Nulla vel est et ipsum consectetur tincidunt. Nam non bibendum elit.</p>
<p>Nunc euismod mi sed diam fermentum, sit amet luctus nibh elementum. Integer lobortis bibendum ipsum. Ut vitae vulputate felis, et varius enim. Praesent ipsum metus, pellentesque vitae metus at, accumsan dignissim leo. Praesent congue urna sit amet lectus laoreet sagittis. Praesent tempor, leo eget ullamcorper mattis, quam nulla porttitor arcu, at gravida leo ante nec sapien. Ut vitae leo sollicitudin, cursus massa vitae, iaculis nibh. Phasellus a sem vel ipsum finibus euismod ac in purus. In urna enim, vulputate sit amet molestie vel, rutrum non tortor. Praesent sodales ex lacus, et luctus nunc dignissim vitae. Aliquam rutrum nulla fringilla venenatis congue. Sed ultricies congue metus in mattis. Proin finibus viverra risus. Aenean consectetur enim auctor enim tincidunt, sed gravida ante porta.</p>
<p>Suspendisse porta magna est, ut vestibulum tortor luctus vitae. Aenean quis laoreet metus. Vestibulum non faucibus odio. Fusce ultricies, est non scelerisque porttitor, felis massa placerat dolor, ac condimentum purus tortor vitae lacus. Etiam eget eros ex. Quisque vulputate sollicitudin odio aliquam efficitur. Nulla vulputate elementum metus, a sollicitudin enim mattis nec. Donec vitae vestibulum erat.</p>
</div>', N'Speed-Demon - Contact', N'This is where the meta description goes.', N'this, is, where, the, meta, keywords, go', N'_SpeedDemon.cshtml', CONVERT(datetime, '2015-10-05 19:15:00', 120), '1', '1', N'_DefaultBody.cshtml');
INSERT INTO Pages (pName, pTitle, pText, mTitle, mDescription, mKeywords, pMasterPage, pEditDate, pBody, pHTML, pBodyFile) VALUES (N'blog', N'Blog', '<div class="post">
<h2 class="title"><a href="#">Sed lacus</a></h2>
<p class="meta">Posted by <a href="#">Someone</a> on January 31, 2012 &nbsp;&bull;&nbsp; <a class="comments" href="#">Comments (64)</a> &nbsp;&bull;&nbsp; <a class="permalink" href="#">Full article</a></p>
<div class="entry">
<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc.</p>
<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum ipsum. Proin imperdiet est. Phasellus dapibus semper urna. Pellentesque ornare, orci in felis. Donec ut ante. In id eros. Suspendisse lacus turpis, cursus egestas at sem.</p>
</div>
</div>
<div class="post">
<h2 class="title"><a href="#">Lorem ipsum sed aliquam</a></h2>
<p class="meta">Posted by <a href="#">Someone</a> on January 8, 2012 &nbsp;&bull;&nbsp; <a class="comments" href="#">Comments (64)</a> &nbsp;&bull;&nbsp; <a class="permalink" href="#">Full article</a></p>
<div class="entry">
<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Phasellus <a href="#">dapibus semper urna</a>. Pellentesque ornare, consectetuer nisl felis ac diam. Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. Mauris vitae nisl nec metus placerat consectetuer.</p>
</div>
</div>
<div class="post">
<h2 class="title"><a href="#">Phasellus pellentesque turpis </a></h2>
<p class="meta">Posted by <a href="#">Someone</a> on January 8, 2012 &nbsp;&bull;&nbsp; <a class="comments" href="#">Comments (64)</a> &nbsp;&bull;&nbsp; <a class="permalink" href="#">Full article</a></p>
<div class="entry">
<p>Sed lacus. Donec lectus. Nullam pretium nibh ut turpis. Nam bibendum. In nulla tortor, elementum vel, tempor at, varius non, purus. Mauris vitae nisl nec metus placerat consectetuer. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc. Donec ipsum. Proin imperdiet est. Pellentesque ornare, orci in consectetuer hendrerit, urna elit eleifend nunc.</p>
</div>
</div>
<div style="clear: both;">&nbsp;</div>', N'Speed-Demon - Blog', N'This is where the meta description goes.', N'this, is, where, the, meta, keywords, go', N'_SpeedDemon.cshtml', CONVERT(datetime, '2015-10-05 21:16:31', 120), '1', '1', N'_NoTitleBody.cshtml');
COMMIT
GO
